#!/bin/bash
#Script générique pour réaliser un backup d'une base de donnee MySQL
#Susceptible d'etre ajouter dans une tache cron

#Couleur affichage
VERT="\\033[1;32m"
NORMAL="\\033[0;39m"
ROUGE="\\033[1;31m"
ROSE="\\033[1;35m"
BLEU="\\033[1;34m"
BLANC="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"

#Variables globales
USER=""
PWD=""
HOST=""
PORT=0000
DATABASE=""
DIRECTORY_DUMP=""
NAME=""
TARGET=""
PORTSSH=22
VERBOSE=false
KEEP=false
DATE=`date +"%Y"-"%m"-"%d"`

function usage(){
  echo -e "Utilisation du script :"
  echo -e "\tAfficher l'aide"
  echo -e "-u\tNom de l'utilisateur de la database"
  echo -e "-m\tMot de passe de l'utilisateur de la database"
  echo -e "-h\tHote contenant la database a backuper"
  echo -e "-p\tPort d'ecoute de la database (default: 3306)"
  echo -e "-d\tNom de la database"
  echo -e "-n\tNom du Backup (default: Nom de la database)"
  echo -e "-f\tDossier du backup si l'on ne désire pas un DUMP distant"
  echo -e "-t\tChemin de sauvegarde de l hote distant"
  echo -e "-k\tGarder la sauvegarde en local aussi si l'option de transfert est activée"
  echo -e "-P\tPort SSH de l hote distant (default : 22)"
  echo -e "-v\tMode verbeux"
  echo -e "\nExemple utilisation"
  echo -e "\n#Si l'on veut un DUMP distant"
  echo -e "script_backup_mysql -u glpi_user -m glpi -h 192.168.1.1 -d glpinew -n glpi-backup -t root@192.168.1.1:/mnt/backup_server/backup_mysql/glpinew/"
  echo -e "\n#Si l'on veut un DUMP local"
  echo -e "script_backup_mysql -u glpi_user -m glpi -h 192.168.1.1 -d glpinew -n glpi-backup -f /opt/backup/glpi/"
  echo -e "\nIMPORTANT\nPensez à copier la clef public sur le serveur que vous desirer envoyer le backup ( Pour automatiser la tache de backup)"
  echo -e "[user@ordi ~]$ ssh-copy-id -i ~/.ssh/id_dsa.pub root@serveur-distant"
  exit 0

}

#Fonction pour afficher le debug
#$1 = 0 ou 1 ( 1 pour afficher l'heure dans le message de debug"
#$2 = Message à afficher
function verbose(){
        if $VERBOSE;
        then
                if [ $1 -eq 1 ]
                then
                        #Affichage de debug
                horodate=`date +"\n%d"/"%m"/"%Y"-"%H":"%M":"%S -- "`
                echo -e "$horodate$2"
        else
                        echo -e "$2"
                fi;
        fi;
}

if [ $# -eq 0 ]
then
  usage
fi


while getopts u:m:kvp:h:d:n:t:f:P: option
do
 case $option in
  u)
    USER=$OPTARG
   ;;
  m)
   PWD=$OPTARG
   ;;
  h)
   HOST=$OPTARG
   ;;
  p)
   PORT=$OPTARG
   ;;
  d)
   DATABASE=$OPTARG
   ;;
  n)
   NAME=$OPTARG
   ;;
  f)
   DIRECTORY_DUMP=$OPTARG
   ;;
  t)
   TARGET=$OPTARG
   ;;
  P)
   PORTSSH=$OPTARG
   ;;
  v)
   VERBOSE=true
    ;;
  k)
        KEEP=true
        ;;
  *)
    usage
    ;;
 esac
done

#Changement du numero de port
#Si pas precise alors port = 3306
if [ $PORT -eq 0000 ]
then
      PORT=3306
fi

#Assignation du fichier de backup et generation de la date
if [ -z $NAME ]
then
        NAME_FILE=${DATABASE}-${DATE}.bck
else
        NAME_FILE=${NAME}-${DATE}.bck
fi

#Affichage Parametre et Requetes selon les parametres envoye
if [ -z $TARGET ]
then
        #Si pas de TARGET et pas de dossier de destination renseigne, dossier du DUMP = /tmp
        if [ -z $DIRECTORY_DUMP ]
        then
                verbose 1 "\nListing des parametres :\n\tUser : $USER\n\tMot de passe : $PWD\n\tHote : $HOST\n\tPort : $PORT\n\tDatabase : $DATABASE\n\tNom : $NAME_FILE\n\tDestination : /tmp\n\tKeep : $KEEP"
                verbose 0 "\nRequete SQL : mysqldump -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > /tmp/$NAME_FILE"
        else
                verbose 1 "\nListing des parametres :\n\tUser : $USER\n\tMot de passe : $PWD\n\tHote : $HOST\n\tPort : $PORT\n\tDatabase : $DATABASE\n\tNom : $NAME_FILE\n\tDestination : $DIRECTORY_DUMP\n\tKeep : $KEEP"
                verbose 0 "\nRequete SQL : mysqldump -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > $DIRECTORY_DUMP$NAME_FILE"
        fi
else
        if [ -z $DIRECTORY_DUMP ]
        then
                verbose 1 "\nListing des parametres :\n\tUser : $USER\n\tMot de passe : $PWD\n\tHote : $HOST\n\tPort : $PORT\n\tDatabase : $DATABASE\n\tNom : $NAME_FILE\n\tDestination : $TARGET\n\tPort SSH : $PORTSSH\n\tKeep : $KEEP"
                verbose 0 "\nRequete SQL : mysqldump -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > /tmp/$NAME_FILE"
        else
                verbose 1 "\nListing des parametres :\n\tUser : $USER\n\tMot de passe : $PWD\n\tHote : $HOST\n\tPort : $PORT\n\tDatabase : $DATABASE\n\tNom : $NAME_FILE\n\tDossier de backup : $DIRECTORY_DUMP\n\tDestination : $TARGET\n\tPort SSH : $PORTSSH\n\tKeep : $KEEP"
                verbose 0 "\nRequete SQL : mysqldump -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > $DIRECTORY_DUMP$NAME_FILE"
        fi

fi

#Dump de la database
if [ -z $TARGET ]
then
        #Si pas de TARGET et que l'on a pas de determiner le dossier de destination, le DUMP est dans /tmp
        if [ -z $DIRECTORY_DUMP ]
        then
                mysqldump --lock-tables -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > /tmp/$NAME_FILE
        else
                mysqldump --lock-tables -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > $DIRECTORY_DUMP$NAME_FILE
        fi
else
        if [ -z $DIRECTORY_DUMP ]
        then
                mysqldump --lock-tables -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > /tmp/$NAME_FILE
        else
                mysqldump --lock-tables -h $HOST -P $PORT -u $USER -p$PWD $DATABASE > $DIRECTORY_DUMP$NAME_FILE
        fi
fi

if [ $? != 0 ]
then
        verbose 1 "Dump Database \t\t\t$ROUGE[KO]$NORMAL"
else
        verbose 1 "Dump Database \t\t\t$VERT[OK]$NORMAL"
fi

#Copie du  dump vers le serveur renseigne en parametre
#Si pas de TARGET, on ne lance pas la commande scp
if [ -z $TARGET ]
then
        verbose 0 "$VERT\nPas de copie distante$NORMAL"
else
        if [ -z $DIRECTORY_DUMP ]
        then
                verbose 1 "Commande Transfert : scp /tmp/$NAME_FILE $TARGET"
                scp -P $PORTSSH /tmp/$NAME_FILE $TARGET > /dev/null 2>&1
        else
                verbose 1 "Commande Transfert : scp $DIRECTORY_DUMP$NAME_FILE $TARGET"
                scp -P $PORTSSH $DIRECTORY_DUMP$NAME_FILE $TARGET > /dev/null 2>&1
        fi

        if [ $? != 0 ]
        then
                verbose 1 "Transfert Dump \t\t\t$ROUGE[KO]$NORMAL"
        else
                verbose 1 "Transfert Dump \t\t\t$VERT[OK]$NORMAL"
        fi
fi

#Suppresion du dump local
#Si pas de TARGET, on ne supprime pas le DUMP
if [ -z $TARGET ]
then
        verbose 0 "$VERT\nPas de Suppression du DUMP local$NORMAL"
else
        #Si l'option KEEP, on ne supprime pas le Dump local
        if $KEEP;
        then
                verbose 0 "$VERT"
                verbose 0 "Option KEEP : Pas de suppresion du Backup local$NORMAL";
        else
                if [ -z $DIRECTORY_DUMP ]
                then
                        rm -f /tmp/$NAME_FILE
                else
                        rm -f $DIRECTORY_DUMP$NAME_FILE
                fi

                if [ $? != 0 ]
                then
                        verbose 1 "Suppression Dump local \t\t$ROUGE[KO]$NORMAL"
                else
                        verbose 1 "Suppression Dump local \t\t$VERT[OK]$NORMAL"
                fi
        fi
fi
